/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MazeRouteImport } from './routes/maze'
import { Route as IndexRouteImport } from './routes/index'

const MazeRoute = MazeRouteImport.update({
  id: '/maze',
  path: '/maze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maze': typeof MazeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maze': typeof MazeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maze': typeof MazeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maze'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maze'
  id: '__root__' | '/' | '/maze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MazeRoute: typeof MazeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maze': {
      id: '/maze'
      path: '/maze'
      fullPath: '/maze'
      preLoaderRoute: typeof MazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MazeRoute: MazeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
