/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MazeRouteImport } from './routes/maze'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as HugRouteImport } from './routes/hug'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeRoute = MazeRouteImport.update({
  id: '/maze',
  path: '/maze',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const HugRoute = HugRouteImport.update({
  id: '/hug',
  path: '/hug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/hug': typeof HugRoute
  '/letter': typeof LetterRoute
  '/maze': typeof MazeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/hug': typeof HugRoute
  '/letter': typeof LetterRoute
  '/maze': typeof MazeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/hug': typeof HugRoute
  '/letter': typeof LetterRoute
  '/maze': typeof MazeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gallery' | '/hug' | '/letter' | '/maze' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gallery' | '/hug' | '/letter' | '/maze' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/hug'
    | '/letter'
    | '/maze'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  HugRoute: typeof HugRoute
  LetterRoute: typeof LetterRoute
  MazeRoute: typeof MazeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze': {
      id: '/maze'
      path: '/maze'
      fullPath: '/maze'
      preLoaderRoute: typeof MazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hug': {
      id: '/hug'
      path: '/hug'
      fullPath: '/hug'
      preLoaderRoute: typeof HugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  HugRoute: HugRoute,
  LetterRoute: LetterRoute,
  MazeRoute: MazeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
